core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("", include('panel_app.urls')),
    path("assessments/",include('assesments.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

panel_app/urls.py
from django.urls import path

from panel_app.EditResultView import EditResultView

from . import hod_views, staff_views, student_views, views

urlpatterns = [
    
    
    path("", views.login_page, name='login_page'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("get_attendance", views.get_attendance, name='get_attendance'),
    path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    path("logout_user/", views.logout_user, name='user_logout'),
    path("admin_home/", hod_views.admin_home, name='admin_home'),
    path("staff/add", hod_views.add_staff, name='add_staff'),
    path("course/add", hod_views.add_course, name='add_course'),
    path("send_student_notification/", hod_views.send_student_notification,
         name='send_student_notification'),
    path("send_staff_notification/", hod_views.send_staff_notification,
         name='send_staff_notification'),
    path("add_session/", hod_views.add_session, name='add_session'),
    path("admin_notify_student", hod_views.admin_notify_student,
         name='admin_notify_student'),
    path("admin_notify_staff", hod_views.admin_notify_staff,
         name='admin_notify_staff'),
    path("admin_view_profile", hod_views.admin_view_profile,
         name='admin_view_profile'),
    path("check_email_availability", hod_views.check_email_availability,
         name="check_email_availability"),
    path("session/manage/", hod_views.manage_session, name='manage_session'),
    path("session/edit/<int:session_id>",
         hod_views.edit_session, name='edit_session'),
    path("student/view/feedback/", hod_views.student_feedback_message,
         name="student_feedback_message",),
    path("staff/view/feedback/", hod_views.staff_feedback_message,
         name="staff_feedback_message",),
    path("student/view/leave/", hod_views.view_student_leave,
         name="view_student_leave",),
    path("staff/view/leave/", hod_views.view_staff_leave, name="view_staff_leave",),
    path("attendance/view/", hod_views.admin_view_attendance,
         name="admin_view_attendance",),
    path("attendance/fetch/", hod_views.get_admin_attendance,
         name='get_admin_attendance'),
    path("student/add/", hod_views.add_student, name='add_student'),
    path("subject/add/", hod_views.add_subject, name='add_subject'),
    path("staff/manage/", hod_views.manage_staff, name='manage_staff'),
    path("student/manage/", hod_views.manage_student, name='manage_student'),
    path("course/manage/", hod_views.manage_course, name='manage_course'),
    path("subject/manage/", hod_views.manage_subject, name='manage_subject'),
    path("staff/edit/<int:staff_id>", hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:staff_id>",
         hod_views.delete_staff, name='delete_staff'),

    path("course/delete/<int:course_id>",
         hod_views.delete_course, name='delete_course'),

    path("subject/delete/<int:subject_id>",
         hod_views.delete_subject, name='delete_subject'),

    path("session/delete/<int:session_id>",
         hod_views.delete_session, name='delete_session'),

    path("student/delete/<int:student_id>",
         hod_views.delete_student, name='delete_student'),
    path("student/edit/<int:student_id>",
         hod_views.edit_student, name='edit_student'),
    path("course/edit/<int:course_id>",
         hod_views.edit_course, name='edit_course'),
    path("subject/edit/<int:subject_id>",
         hod_views.edit_subject, name='edit_subject'),


    # Staff
    path("staff/home/", staff_views.staff_home, name='staff_home'),
    path("staff/apply/leave/", staff_views.staff_apply_leave,
         name='staff_apply_leave'),
    path("staff/feedback/", staff_views.staff_feedback, name='staff_feedback'),
    path("staff/view/profile/", staff_views.staff_view_profile,
         name='staff_view_profile'),
    path("staff/attendance/take/", staff_views.staff_take_attendance,
         name='staff_take_attendance'),
    path("staff/attendance/update/", staff_views.staff_update_attendance,
         name='staff_update_attendance'),
    path("staff/get_students/", staff_views.get_students, name='get_students'),
    path("staff/attendance/fetch/", staff_views.get_student_attendance,
         name='get_student_attendance'),
    path("staff/attendance/save/",
         staff_views.save_attendance, name='save_attendance'),
    path("staff/attendance/update/",
         staff_views.update_attendance, name='update_attendance'),
    path("staff/fcmtoken/", staff_views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/", staff_views.staff_view_notification,
         name="staff_view_notification"),
    path("staff/result/add/", staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/", EditResultView.as_view(),
         name='edit_student_result'),
    path('staff/result/fetch/', staff_views.fetch_student_result,
         name='fetch_student_result'),


    




    # Student
    path("student/home/", student_views.student_home, name='student_home'),
    path("student/view/attendance/", student_views.student_view_attendance,
         name='student_view_attendance'),
    path("student/apply/leave/", student_views.student_apply_leave,
         name='student_apply_leave'),
    path("student/feedback/", student_views.student_feedback,
         name='student_feedback'),
    path("student/view/profile/", student_views.student_view_profile,
         name='student_view_profile'),
    path("student/fcmtoken/", student_views.student_fcmtoken,
         name='student_fcmtoken'),
    path("student/view/notification/", student_views.student_view_notification,
         name="student_view_notification"),
    path('student/view/result/', student_views.student_view_result,
         name='student_view_result'),

    path('list/', student_views.assessment_list, name='stu_assessment_list'),
    path('stu_assessments/<int:assessment_id>/', student_views.assessment_detail, name='stu_assessment_detail'),
    path('stu_assessments/<int:assessment_id>/take/', student_views.assessment_take, name='stu_assessment_take'),


]

assesments/models.py
from django.db import models

class Assessment(models.Model):
    ASSESSMENT_TYPES = (
        ('quiz', 'Quiz'),
        ('exam', 'Exam'),
        ('assignment', 'Assignment'),
    )
    name = models.CharField(max_length=255)
    type = models.CharField(choices=ASSESSMENT_TYPES, max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    keywords = models.CharField(max_length=255, blank=True, help_text="Comma-separated keywords related to the assessment.")
    difficulty_level = models.CharField(
        max_length=20,
        choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')],
        default=1 
    )
class Question(models.Model):
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE)
    text = models.TextField()

class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.TextField()
    is_correct = models.BooleanField(null=True, blank=True, default=None)

from django.conf import settings

class UserAnswer(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE, related_name="user_answers", null=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=1000) 
    timestamp = models.DateTimeField(auto_now_add=True)
    is_correct = models.BooleanField(null=True, blank=True)
    answer_file = models.FileField(upload_to='user_submissions/', null=True, blank=True)

panel_app/forms.py
from django import forms
from django.forms.widgets import DateInput, TextInput

from .models import *


class FormSettings(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FormSettings, self).__init__(*args, **kwargs)
        # Here make some changes such as:
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'


class CustomUserForm(FormSettings):
    email = forms.EmailField(required=True)
    gender = forms.ChoiceField(choices=[('M', 'Male'), ('F', 'Female')])
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    address = forms.CharField(widget=forms.Textarea)
    password = forms.CharField(widget=forms.PasswordInput)
    widget = {
        'password': forms.PasswordInput(),
    }
    profile_pic = forms.ImageField()

    def __init__(self, *args, **kwargs):
        super(CustomUserForm, self).__init__(*args, **kwargs)

        if kwargs.get('instance'):
            instance = kwargs.get('instance').admin.__dict__
            self.fields['password'].required = False
            for field in CustomUserForm.Meta.fields:
                self.fields[field].initial = instance.get(field)
            if self.instance.pk is not None:
                self.fields['password'].widget.attrs['placeholder'] = "Fill this only if you wish to update password"

    def clean_email(self, *args, **kwargs):
        formEmail = self.cleaned_data['email'].lower()
        if self.instance.pk is None:  # Insert
            if CustomUser.objects.filter(email=formEmail).exists():
                raise forms.ValidationError(
                    "The given email is already registered")
        else:  # Update
            dbEmail = self.Meta.model.objects.get(
                id=self.instance.pk).admin.email.lower()
            if dbEmail != formEmail:  # There has been changes
                if CustomUser.objects.filter(email=formEmail).exists():
                    raise forms.ValidationError("The given email is already registered")

        return formEmail

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'gender',  'password','profile_pic', 'address' ]


class StudentForm(CustomUserForm):
    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)

    class Meta(CustomUserForm.Meta):
        model = Student
        fields = CustomUserForm.Meta.fields + \
            ['course', 'session']


class AdminForm(CustomUserForm):
    def __init__(self, *args, **kwargs):
        super(AdminForm, self).__init__(*args, **kwargs)

    class Meta(CustomUserForm.Meta):
        model = Admin
        fields = CustomUserForm.Meta.fields


class StaffForm(CustomUserForm):
    def __init__(self, *args, **kwargs):
        super(StaffForm, self).__init__(*args, **kwargs)

    class Meta(CustomUserForm.Meta):
        model = Staff
        fields = CustomUserForm.Meta.fields + \
            ['course' ]


class CourseForm(FormSettings):
    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)

    class Meta:
        fields = ['name']
        model = Course


class SubjectForm(FormSettings):

    def __init__(self, *args, **kwargs):
        super(SubjectForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Subject
        fields = ['name', 'staff', 'course']


class SessionForm(FormSettings):
    def __init__(self, *args, **kwargs):
        super(SessionForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Session
        fields = '__all__'
        widgets = {
            'start_year': DateInput(attrs={'type': 'date'}),
            'end_year': DateInput(attrs={'type': 'date'}),
        }


class LeaveReportStaffForm(FormSettings):
    def __init__(self, *args, **kwargs):
        super(LeaveReportStaffForm, self).__init__(*args, **kwargs)

    class Meta:
        model = LeaveReportStaff
        fields = ['date', 'message']
        widgets = {
            'date': DateInput(attrs={'type': 'date'}),
        }


class FeedbackStaffForm(FormSettings):

    def __init__(self, *args, **kwargs):
        super(FeedbackStaffForm, self).__init__(*args, **kwargs)

    class Meta:
        model = FeedbackStaff
        fields = ['feedback']


class LeaveReportStudentForm(FormSettings):
    def __init__(self, *args, **kwargs):
        super(LeaveReportStudentForm, self).__init__(*args, **kwargs)

    class Meta:
        model = LeaveReportStudent
        fields = ['date', 'message']
        widgets = {
            'date': DateInput(attrs={'type': 'date'}),
        }


class FeedbackStudentForm(FormSettings):

    def __init__(self, *args, **kwargs):
        super(FeedbackStudentForm, self).__init__(*args, **kwargs)

    class Meta:
        model = FeedbackStudent
        fields = ['feedback']


class StudentEditForm(CustomUserForm):
    def __init__(self, *args, **kwargs):
        super(StudentEditForm, self).__init__(*args, **kwargs)

    class Meta(CustomUserForm.Meta):
        model = Student
        fields = CustomUserForm.Meta.fields 


class StaffEditForm(CustomUserForm):
    def __init__(self, *args, **kwargs):
        super(StaffEditForm, self).__init__(*args, **kwargs)

    class Meta(CustomUserForm.Meta):
        model = Staff
        fields = CustomUserForm.Meta.fields


class EditResultForm(FormSettings):
    session_list = Session.objects.all()
    session_year = forms.ModelChoiceField(
        label="Session Year", queryset=session_list, required=True)

    def __init__(self, *args, **kwargs):
        super(EditResultForm, self).__init__(*args, **kwargs)

    class Meta:
        model = StudentResult
        fields = ['session_year', 'subject', 'student', 'test', 'exam']

panel_app/views.py
import json
import requests
from django.contrib import messages
from django.contrib.auth import  login, logout
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.views.decorators.csrf import csrf_exempt

from .EmailBackend import EmailBackend
from .models import Attendance, Session, Subject

# Create your views here.


def login_page(request):
    if request.user.is_authenticated:
        if request.user.user_type == '1':
            return redirect(reverse("admin_home"))
        elif request.user.user_type == '2':
            return redirect(reverse("staff_home"))
        else:
            return redirect(reverse("student_home"))
    return render(request, 'panel_app/login.html')

def doLogin(request, **kwargs):
    if request.method != 'POST':
        return HttpResponse("<h4>Denied</h4>")
    else:
        # Authenticate
        user = EmailBackend.authenticate(request, username=request.POST.get('email'), password=request.POST.get('password'))
        if user is not None:
            login(request, user)
            if user.user_type == '1':
                return redirect(reverse("admin_home"))
            elif user.user_type == '2':
                return redirect(reverse("staff_home"))
            else:
                return redirect(reverse("student_home"))
        else:
            # Add an error message
            messages.error(request, "Invalid email or password. Please try again.")
            return redirect("login_page")

def logout_user(request):
    if request.user != None:
        logout(request)
    return redirect("/")


@csrf_exempt
def get_attendance(request):
    subject_id = request.POST.get('subject')
    session_id = request.POST.get('session')
    try:
        subject = get_object_or_404(Subject, id=subject_id)
        session = get_object_or_404(Session, id=session_id)
        attendance = Attendance.objects.filter(subject=subject, session=session)
        attendance_list = []
        for attd in attendance:
            data = {
                    "id": attd.id,
                    "attendance_date": str(attd.date),
                    "session": attd.session.id
                    }
            attendance_list.append(data)
        return JsonResponse(json.dumps(attendance_list), safe=False)
    except Exception as e:
        return None


def showFirebaseJS(request):
    data = """
    // Give the service worker access to Firebase Messaging.
// Note that you can only use Firebase Messaging here, other Firebase libraries
// are not available in the service worker.
importScripts('https://www.gstatic.com/firebasejs/7.22.1/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/7.22.1/firebase-messaging.js');

// Initialize the Firebase app in the service worker by passing in
// your app's Firebase config object.
// https://firebase.google.com/docs/web/setup#config-object
firebase.initializeApp({
    apiKey: "AIzaSyBarDWWHTfTMSrtc5Lj3Cdw5dEvjAkFwtM",
    authDomain: "sms-with-django.firebaseapp.com",
    databaseURL: "https://sms-with-django.firebaseio.com",
    projectId: "sms-with-django",
    storageBucket: "sms-with-django.appspot.com",
    messagingSenderId: "945324593139",
    appId: "1:945324593139:web:03fa99a8854bbd38420c86",
    measurementId: "G-2F2RXTL9GT"
});

// Retrieve an instance of Firebase Messaging so that it can handle background
// messages.
const messaging = firebase.messaging();
messaging.setBackgroundMessageHandler(function (payload) {
    const notification = JSON.parse(payload);
    const notificationOption = {
        body: notification.body,
        icon: notification.icon
    }
    return self.registration.showNotification(payload.notification.title, notificationOption);
});
    """
    return HttpResponse(data, content_type='application/javascript')

panel_app/templates/student_template/assessment_detail.html
{% extends 'panel_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}
<div class="container mt-5">
    {% comment %} {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <p class="text-success"{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %} {% endcomment %}
    
    <h2 class="text-center mb-4">{{ assessment.name }}</h2>

    {% if has_taken_assessment %}
    <div class="alert alert-info" role="alert">
        You have already taken this assessment.

        {% if assessment.type == "assignment" %}
    <p><strong>Your uploaded assignment file:</strong> <a href="{{ user_assignment.answer_file.url }}" target="_blank" download>Download it here</a>.</p>
    <ul>
        {% for user_answer in user_answers %}
            <li>
                Status: 
                {% if user_answer.is_correct == True %}
                    <h3 class="text-success">Checked</h3>
                {% elif user_answer.is_correct == False %}
                    <h3 class="text-danger">Not checked Yet.</h3>
                    <form method="post" action="{% url 'stu_assessment_take' assessment.id %}">
                        {% csrf_token %}
                        {% for option in user_answer.question.option_set.all %}
                            <input type="radio" name="answer_for_{{ user_answer.question.id }}" value="{{ option.id }}"> 
                            {{ option.text }} 
                        {% endfor %}
                        <input type="submit" value="Submit Answer">
                    </form>
                {% else %}
                    <p class = "text-warning">Pending review....</p>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% elif assessment.type == "exam" %}
        Here are your answers:
        <ul>
            {% for user_answer in user_answers %}
            <li>
                Question: {{ user_answer.question.text }}
                <br>
                Your Answer: {{ user_answer.answer }}
                <br>
                Status: 
                {% if user_answer.is_correct == True %}
                    <p class="text-success">Checked</p>
                {% elif user_answer.is_correct == False %}
                    <p class "text-danger">Not Checked Yet</p>
                {% else %}
                    <p class = "text-warning">Pending review....</p>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    {% else %}
        <form method="post" action="{% url 'stu_assessment_take' assessment.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% for item in questions_with_options %}
            <div class="card mb-4">
                <div class="card-header bg-primary text-white">
                    {{ item.question.text }}
                </div>
                <div class="card-body">
                    {% if assessment.type == "assignment" %}
                    <div>
                        <label for="file_for_{{ item.question.id }}">Upload Assignment:</label>
                        <input type="file" id="file_for_{{ item.question.id }}" name="file_for_{{ item.question.id }}">
                    </div>
                    {% elif assessment.type == "exam" %}
                    <div class="form-group">
                        <label for="text_answer_for_{{ item.question.id }}" class="form-label">Your Answer:</label>
                        <textarea class="form-control" id="text_answer_for_{{ item.question.id }}" name="text_answer_for_{{ item.question.id }}" rows="5"></textarea>
                    </div>
                    
                    {% else %}
                    <ul class="list-group mb-3">
                        {% for option in item.options %}
                        <li class="list-group-item">
                            <input type="radio" name="answer_for_{{ item.question.id }}" value="{{ option.id }}"> 
                            {{ option.text }} 
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            <div class="text-center">
                <input type="submit" value="Submit" class="btn btn-primary">
            </div>
        </form>
    {% endif %}
</div>
{% endblock %}

panel_app/templates/student_template/assessment_list.html
{% extends 'panel_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">

            
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2>Assessments DashBoard</h2>
            </div>
            
           
            {% for assessment in assessments %}
            {% if assessment.type == "assignment" %}
            <div class="mb-3 bg-info w-50">
                <a href="{% url 'stu_assessment_detail' assessment.id %}" class="btn btn-block {{ assessment.type|lower }}-btn">{{ assessment.name }}</a>
            </div>

            {% elif assessment.type == "exam" %}
            <div class="mb-3 w-50 bg-warning ">
                <a href="{% url 'stu_assessment_detail' assessment.id %}" class="btn btn-block {{ assessment.type|lower }}-btn">{{ assessment.name }}</a>
            </div>
            {% elif assessment.type == "quiz" %}
            <div class="mb-3 w-50 bg-success">
                <a href="{% url 'stu_assessment_detail' assessment.id %}" class="btn btn-block {{ assessment.type|lower }}-btn">{{ assessment.name }}</a>
            </div>
            {% else %}
            <div class="mb-3">
                <a href="{% url 'stu_assessment_detail' assessment.id %}" class="btn btn-block {{ assessment.type|lower }}-btn">{{ assessment.name }}</a>
            </div>
            {% endif %}
                
            {% endfor %}
        </div>
        <div class="legend col-md-4">
            <div class="mb-3 bg-info w-25">
                <span class="legend-text">Assignment</span>
            </div>
            <div class="mb-3 w-25 bg-warning ">
                <span class="legend-text">Exam</span>
            </div>
            <div class="mb-3 w-25 bg-success">
                <span class="legend-text">Quiz</span>
            </div>
        </div>
    </div>
</div>

{% endblock %}

panel_app/templates/student_template/student_apply_leave.html
{% extends 'panel_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "panel_app/form_template.html" with messages=messages  form=form button_text="Apply For Leave"%}
                </div>
                <!-- /.card -->
<div class="card card-dark">
    <div class="card-header"><h3 class="card-title">Leave History</h3></div>
   <div class="table">

       <table class="table table-bordered">
           <tr>
               <th>ID</th>
               <th>Date</th>
               <th>Message</th>
                <th>Status</th>
        </tr>
        {% for leave in leave_history %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{leave.date}}</td>
              <td>{{leave.message}}</td>
              <td>
                  
                  {% if leave.status == 0 %}
                  <span class="badge badge-warning">Pending</span>
                  {% elif leave.status == 1 %}
                  <span class="badge badge-success">Accepted</span>
                  
                    {% else %}
                    <span class="badge badge-danger">Rejected</span>
                    
                    {% endif %}
                    
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

panel_app/templates/student_template/student_feedback.html
{% extends 'panel_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "panel_app/form_template.html" with messages=messages  form=form button_text="Submit Feedback"%}
                </div>
                <!-- /.card -->
<div class="card card-dark">
    <div class="card-header"><h3 class="card-title">{{page_title}}</h3>
    </div>
   <div class="table p-2">

       <table class="table table-bordered">
           <tr>
               <th>ID</th>
               <th>Feedback</th>
               <th>Reply</th>
            <th>Created At</th>
        </tr>
        {% for feedback in feedbacks %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{feedback.feedback}}</td>
            <td>
                  
                {% if feedback.reply == "" %}
                    <p class="badge badge-warning">No Response Yet</p>
                    {% else %}
                    {{feedback.reply}}
                {% endif %}
                    
            </td>              <td>{{feedback.created_at}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

panel_app/templates/student_template/student_view_notification.html
{% extends 'panel_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>


                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">



                       


                        <div class="form-group table">
              <table class="table table-bordered">
                  <tr>
                      <th>#</th>
                      <th>Date</th>
                      <th>Message</th>
                  </tr>
                  {% for notification in  notifications %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{notification.created_at}}</td>
                        <td>{{notification.message}}</td>
                    </tr>
                  {% endfor %}
              </table>
                        </div>
                   
                    </div>
                    <!-- /.card-body -->

                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

panel_app/templates/student_template/take_quiz.html
<!-- take_quiz.html -->

{% extends 'panel_app/base.html' %}
{% block page_title %}Take Quiz - {{ assessment.title }}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">Take Quiz - {{ assessment.title }}</h3>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% for question in questions %}
                            <div class="form-group">
                                <label>{{ question.text }}</label>
                                {% if question.is_multiple_choice %}
                                <div class="form-check">
                                    {% for option in question.option_set.all %}
                                    <input type="radio" id="option{{ option.id }}" name="question{{ question.id }}" value="{{ option.id }}" class="form-check-input">
                                    <label for="option{{ option.id }}" class="form-check-label">{{ option.text }}</label><br>
                                    {% endfor %}
                                </div>
                                {% else %}
                                <textarea name="question{{ question.id }}" id="question{{ question.id }}" rows="4" class="form-control"></textarea>
                                {% endif %}
                            </div>
                            {% endfor %}
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}